# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

# Maximum width of each line (Default: 100)
max_width = 96

# Use tab characters for indentation, spaces for alignment (Default: false)
hard_tabs = false

# Number of spaces per tab (Default: 4)
tab_spaces = 4

# Unix or Windows line endings [Auto|Windows|Unix|Native] (Default: Auto)
newline_style = "Auto"

# Whether to use different formatting for items and expressions if they satisfy a heuristic
# notion of 'small' [Off|Max|Default] (Default: Default)
use_small_heuristics = "Max"

# Maximum width of the args of a function call before falling back to vertical formatting.
# (Default: 60)
# fn_call_width = 60 # overridden by use_small_heuristics = "Max"

# Maximum width of the args of a function-like attributes before falling back to vertical
# formatting. (Default: 70)
# attr_fn_like_width = 70 # overridden by use_small_heuristics = "Max"

# Maximum width in the body of a struct lit before falling back to vertical formatting.
# (Default: 18)
# struct_lit_width = 18 # overridden by use_small_heuristics = "Max"

# Maximum width in the body of a struct variant before falling back to vertical formatting.
# (Default: 35)
# struct_variant_width = 35 # overridden by use_small_heuristics = "Max"

# Maximum width of an array literal before falling back to vertical formatting. (Default: 60)
# array_width = 60 # overridden by use_small_heuristics = "Max"

# Maximum length of a chain to fit on a single line. (Default: 60)
# chain_width = 60 # overridden by use_small_heuristics = "Max"

# Maximum line length for single line if-else expressions. A value of zero means always break
# if-else expressions. (Default: 50)
# single_line_if_else_max_width = 50 # overridden by use_small_heuristics = "Max"

# Reorder import and extern crate statements alphabetically (Default: true)
reorder_imports = true

# Reorder module statements alphabetically in group (Default: true)
reorder_modules = true

# Remove nested parens (Default: true)
remove_nested_parens = true

# Determines whether leading pipes are emitted on match arms [Always|Never|Preserve]
# (Default: Never)
match_arm_leading_pipes = "Never"

# Control the layout of arguments in a function [Compressed|Tall|Vertical] (Default: Tall)
fn_args_layout = "Compressed"

# The edition of the parser (RFC 2052) [2015|2018|2021] (Default: 2015)
edition = "2021"

# Merge multiple `#[derive(...)]` into a single one (Default: true)
merge_derives = true

# Replace uses of the try! macro by the ? shorthand (Default: false)
use_try_shorthand = false

# Use field initialization shorthand if possible (Default: false)
use_field_init_shorthand = false

# Always print the abi for extern items (Default: true)
force_explicit_abi = true

# Prints the names of mismatched files that were formatted. Prints the names of files that
# would be formated when used with `--check` mode (Default: false)
print_misformatted_file_names = true
