[build]
incremental = false
rustflags = [
    "-W", "clippy::all",
#    "-W", "clippy::pedantic",
    "-W", "absolute_paths_not_starting_with_crate",
    "-W", "box_pointers",
    "-W", "deprecated_in_future",
    "-W", "elided_lifetimes_in_paths",
    "-W", "explicit_outlives_requirements",
    "-W", "keyword_idents",
    "-W", "macro_use_extern_crate",
    "-W", "meta_variable_misuse",
    "-W", "missing_abi",
    "-W", "missing_copy_implementations",
    "-W", "missing_debug_implementations",
#    "-W", "missing_docs",
    "-W", "non_ascii_idents",
    "-W", "noop_method_call",
    "-W", "pointer_structural_match",
    "-W", "rust_2018_idioms",
    "-W", "rust_2021_incompatible_closure_captures",
    "-W", "rust_2021_incompatible_or_patterns",
    "-W", "rust_2021_prefixes_incompatible_syntax",
    "-W", "rust_2021_prelude_collisions",
    "-W", "single_use_lifetimes",
    "-W", "trivial_numeric_casts",
    "-W", "unreachable_pub",
    "-W", "unsafe_code",
    "-W", "unsafe_op_in_unsafe_fn",
    "-W", "unstable_features",
    "-W", "unused_crate_dependencies",
    "-W", "unused_extern_crates",
    "-W", "unused_import_braces",
    "-W", "unused_lifetimes",
    "-W", "unused_qualifications",
    "-W", "unused_results",
    "-W", "variant_size_differences",
    "-C", "link-dead-code",
#    "-C", "overflow-checks=off",
#    "-C", "panic=abort",
#    "-Z", "profile",
#    "-Z", "panic_abort_tests"
]
rustdocflags = [ "-C", "panic=abort" ]

[env]
#CARGO_INCREMENTAL = "0"
#RUSTFLAGS = "-C link-dead-code -C overflow-checks=off -C panic=abort -Z profile -Z panic_abort_tests"
#RUSTDOCFLAGS = "-C panic=abort"
